### ISSUE TITLE
game was crash

### ISSUE THREAD

**Issue by qianbing233** [Nomi-CEu/Nomi-CEu#492]
### Nomi CEu Version

1.7-alpha-1

### Launcher

Plain Craft Launcher 2

### Configurations or Mods Changed

mcjtylib-1.12-3.5.4 (1)
xnet-1.12-1.8.2-zh_cn-2023-5-3
jecharacters-1.12.0-3.7.2
hecharacters-1.12.2-1.4.0 (1)
Fluid+Craft+for+AE2-2.4.12-r
FluxNetworks-1.12.2-4.1.1.34
[平滑字体] SmoothFont-mc1.12.2-2.1.4

### Environment

singleplayer

### Mode

Normal Mode

### What Happened

I lauch game when i wait a few time  game was crashed

### Expected Behavior

i dont konw 

### Logs

[08:17:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[08:17:49] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[08:17:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[08:17:49] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[08:17:49] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_381, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre-1.8
[08:17:49] [main/INFO] [FML]: Searching F:\minecraft\versions\nomi-ceu 1.7 alpha 1\mods for mods
[08:17:49] [main/INFO] [FML]: Searching F:\minecraft\versions\nomi-ceu 1.7 alpha 1\mods\1.12.2 for mods
[08:17:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in !configanytime-1.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:49] [main/WARN] [FML]: The coremod com.cleanroommc.configanytime.ConfigAnytimePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:49] [main/WARN] [FML]: The coremod ConfigAnytimePlugin (com.cleanroommc.configanytime.ConfigAnytimePlugin) is not signed!
[08:17:49] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from !mixinbooter-8.6.jar
[08:17:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in [平滑字体] SmoothFont-mc1.12.2-2.1.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:49] [main/WARN] [FML]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:49] [main/WARN] [FML]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
[08:17:49] [main/WARN] [FML]: The coremod -Bansoukou- (zone.rong.bansoukou.BansoukouCoreMod) is not signed!
[08:17:49] [main/INFO] [Bansoukou]: Ikimasu!
[08:17:49] [main/WARN] [Bansoukou]: Draconic-Evolution-1.12.2-2.3.28.354-universal.jar was found in the mods folder. Copying to modify the copied cache.
[08:17:49] [main/WARN] [Bansoukou]: Marking file:/F:/minecraft/versions/nomi-ceu%201.7%20alpha%201/mods/Draconic-Evolution-1.12.2-2.3.28.354-universal.jar to fool Forge's mod discovering mechanism.
[08:17:49] [main/WARN] [Bansoukou]: NuclearCraft-2.18y-1.12.2.jar was found in the mods folder. Copying to modify the copied cache.
[08:17:49] [main/WARN] [Bansoukou]: Marking file:/F:/minecraft/versions/nomi-ceu%201.7%20alpha%201/mods/NuclearCraft-2.18y-1.12.2.jar to fool Forge's mod discovering mechanism.
[08:17:49] [main/WARN] [Bansoukou]: Patching assets/draconicevolution/lang/en_US.lang...
[08:17:49] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/blocks/InvisECoreBlock.class...
[08:17:49] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/blocks/tileentity/TileEnergyCoreStabilizer.class...
[08:17:49] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/blocks/tileentity/TileEnergyStorageCore.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/blocks/tileentity/TileInvisECoreBlock.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/client/gui/GuiEnergyCore.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/inventory/ContainerReactor$SlotReactor.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/inventory/ContainerReactor.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/items/ToolUpgrade.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/lib/EnergyCoreBuilder.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/utils/BlockStateMultiblockHelper.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/utils/BlockStateMultiblockStorage.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching com/brandon3055/draconicevolution/world/EnergyCoreStructure.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching nc/integration/gtce/GTCERecipeHelper.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching nc/recipe/AbstractRecipeHandler.class...
[08:17:50] [main/WARN] [Bansoukou]: Patching nc/recipe/RecipeTupleGenerator.class...
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AdvancedRocketry-1.12.2-1.7.0-232-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod AdvancedRocketryPlugin (zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in appliedenergistics2-rv6-stable-7-extended_life-v0.55.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod AE2ELCore (appeng.core.AE2ELCore) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in bogosorter-1.4.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod BogoSorter-Core (com.cleanroommc.bogosorter.core.BogoSorterCore) is not signed!
[08:17:50] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from censoredasm5.18.jar
[08:17:50] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CreativeCore_v1.10.71_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod CreativePatchingLoader (com.creativemd.creativecore.core.CreativePatchingLoader) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Fluid+Craft+for+AE2-2.4.12-r.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod FluidCraftCore (com.glodblock.github.coremod.FCCoreMod) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in gregtech-1.12.2-2.7.4-beta.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod GregTechLoadingPlugin (gregtech.asm.GregTechLoadingPlugin) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in groovyscript-0.6.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod GroovyScript-Core (com.cleanroommc.groovyscript.core.GroovyScriptCore) is not signed!
[08:17:50] [main/WARN] [FML]: The coremod me.towdium.hecharacters.core.HechCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod HechCore (me.towdium.hecharacters.core.HechCore) is not signed!
[08:17:50] [main/WARN] [FML]: The coremod me.towdium.jecharacters.core.JechCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod JechCore (me.towdium.jecharacters.core.JechCore) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in JEI-Utilities-1.12.2-0.2.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod com.github.vfyjxf.jeiutilities.asm.JeiUtilitiesLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod JeiUtilitiesLoadingPlugin (com.github.vfyjxf.jeiutilities.asm.JeiUtilitiesLoadingPlugin) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in librarianlib-1.12.2-4.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod com.teamwizardry.librarianlib.asm.LibLibCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod LibrarianLib Plugin (com.teamwizardry.librarianlib.asm.LibLibCorePlugin) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in LittleTiles_v1.5.81_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod com.creativemd.littletiles.LittlePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod LittlePatchingLoader (com.creativemd.littletiles.LittlePatchingLoader) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in modularui-2.2.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod ModularUI-Core (com.cleanroommc.modularui.core.ModularUICore) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in nae2-1.3.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod NAE2-Core (co.neeve.nae2.NAE2MixinPlugin) is not signed!
[08:17:50] [main/WARN] [FML]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod RBLoadingPlugin (pw.prok.realbench.asm.RBLoadingPlugin) is not signed!
[08:17:50] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[08:17:50] [main/WARN] [FML]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod io.dogboy.serializationisbad.legacyforge.SerializationIsBadCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:17:50] [main/WARN] [FML]: The coremod serializationisbad (io.dogboy.serializationisbad.legacyforge.SerializationIsBadCoreMod) is not signed!
[08:17:50] [main/INFO] [io.dogboy.serializationisbad.core.SerializationIsBad]: Initializing SerializationIsBad, implementation type: legacyforge
[08:17:50] [main/ERROR] [io.dogboy.serializationisbad.core.SerializationIsBad]: Failed to load remote config file
java.net.UnknownHostException: raw.githubusercontent.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_381]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_381]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_381]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_381]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_381]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_381]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_381]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:1.8.0_381]
	at io.dogboy.serializationisbad.core.SerializationIsBad.readRemoteConfig(SerializationIsBad.java:134) [serializationisbad-1.5.jar:1.5]
	at io.dogboy.serializationisbad.core.SerializationIsBad.readConfig(SerializationIsBad.java:112) [serializationisbad-1.5.jar:1.5]
	at io.dogboy.serializationisbad.core.SerializationIsBad.<init>(SerializationIsBad.java:63) [serializationisbad-1.5.jar:1.5]
	at io.dogboy.serializationisbad.core.SerializationIsBad.init(SerializationIsBad.java:45) [serializationisbad-1.5.jar:1.5]
	at io.dogboy.serializationisbad.legacyforge.SerializationIsBadCoreMod.<init>(SerializationIsBadCoreMod.java:19) [serializationisbad-1.5.jar:1.5]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_381]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_381]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_381]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_381]
	at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_381]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) [forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_381]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?]
[08:17:50] [main/INFO] [io.dogboy.serializationisbad.core.SerializationIsBad]: Using local config file as a fallback
[08:17:50] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at F:\minecraft\versions\nomi-ceu 1.7 alpha 1 for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_381]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?]
Caused by: java.lang.RuntimeException: You are currently using SerializationIsBad without any patch modules configured. The mod on its own doesn't do anything so please install a config file patching the vulnerabilities
	at io.dogboy.serializationisbad.core.SerializationIsBad.<init>(SerializationIsBad.java:65) ~[serializationisbad-1.5.jar:1.5]
	at io.dogboy.serializationisbad.core.SerializationIsBad.init(SerializationIsBad.java:45) ~[serializationisbad-1.5.jar:1.5]
	at io.dogboy.serializationisbad.legacyforge.SerializationIsBadCoreMod.<init>(SerializationIsBadCoreMod.java:19) ~[serializationisbad-1.5.jar:1.5]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_381]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_381]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_381]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_381]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_381]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 11 more
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.reflect.InvocationTargetException
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:17:50] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 6 more

**Comment by MatthiasMann** [comment]
This is the error reason:
```
[08:17:50] [main/ERROR] [io.dogboy.serializationisbad.core.SerializationIsBad]: Failed to load remote config file
java.net.UnknownHostException: raw.githubusercontent.com
```

Is that website blocked?

**Comment by Folanlron** [comment]
If you are playing single player you can just disable SerialIsBad mod..

We can't do anything about network issues..

**Comment by qianbing233** [comment]
Ok i try to it

**Comment by qianbing233** [comment]
Oh，it is fixed

**Comment by IntegerLimit** [comment]
Doesn't look like 1.7.1-a-1, but anyways. Closing.

Note: Next time please wrap the log in a code block.
