### ISSUE TITLE
Groovy script error on server side

### ISSUE THREAD

**Issue by lynxx131** [Nomi-CEu/Nomi-CEu#670]
### Nomi CEu Version

Nightly

### Launcher

Prism Launcher

### Environment

Linux dedicated server running `dev/gt-2.8-8bfeaad`, issue only occurs on a dedicated server and does not happen in single player.

### Mode

Expert Mode

### What Happened

When a standalone server instance tries to run `diodes.groovy` it encounters the following error:

```
[10:44:15] [SERVER/ERROR] [nomiceu]: An exception occurred while running scripts. Look at latest.log for a full stacktrace:
        java.lang.TypeNotPresentException: Type net.minecraft.client.renderer.texture.TextureAtlasSprite not present
                at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
                at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
                at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
                at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
                at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
                at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
                at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
                at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
                at java.beans.FeatureDescriptor.getReturnType(FeatureDescriptor.java:370)
                at java.beans.Introspector.getTargetEventInfo(Introspector.java:1052)
                at java.beans.Introspector.getBeanInfo(Introspector.java:427)
                at java.beans.Introspector.getBeanInfo(Introspector.java:173)
                at java.beans.Introspector.getBeanInfo(Introspector.java:260)
                at java.beans.Introspector.<init>(Introspector.java:407)
                at java.beans.Introspector.getBeanInfo(Introspector.java:173)
                at groovy.lang.MetaClassImpl.lambda$addProperties$25(MetaClassImpl.java:3465)
                at java.security.AccessController.doPrivileged(Native Method)
                at groovy.lang.MetaClassImpl.doPrivileged(MetaClassImpl.java:3497)
                at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3465)
                at groovy.lang.MetaClassImpl.reinitialize(MetaClassImpl.java:3447)
                at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3440)
                at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:272)
                at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:314)
                at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:324)
                at diodes.replaceRecipe(diodes.groovy:28)
                in diodes.groovy in line 18
                at com.cleanroommc.groovyscript.sandbox.GroovySandbox.loadScripts(GroovySandbox.java:142)
```

### Expected Behavior

Groovy script should run without error

### Reproduction Steps

1. Stand up a dedicated server instance
2. Connect to it
3. Observe groovy error in chat and in the groovy log file on the server

**Comment by IntegerLimit** [comment]
Fixed by [`7a45e40` (#619)](https://github.com/Nomi-CEu/Nomi-CEu/pull/619/commits/7a45e40c281431d7f3378d36223eb95a9135d2b8),
