### ISSUE TITLE
Draconium Ore not spawning in The End?

### ISSUE THREAD

**Issue by Powah101** [Nomi-CEu/Nomi-CEu#710]
### Nomi CEu Version

1.7-alpha-4

### Launcher

Prism Launcher

### Configurations or Mods Changed

Also have the additonal mods that are listed in the Nomifactory curse forge page. Compact machines, Flux Networks etc...

### Environment

Single player

### Mode

Normal Mode

### What Happened

Got to the end for the first time. Been flying around for about 2hours and not seen a single Draconium Ore. Tried scanning, auto miners and flying around for hours.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/89583978/08c8dfc3-0030-45bd-bc9e-7988adde3452)

### Expected Behavior

Quest book and other discord members mention having seen a lot of Draconium, I've not seen or scanned a single ore.

### Reproduction Steps

Generated The End biome in the latest alpha version

**Comment by Powah101** [comment]
Update on this, looks like ore spawn is disabled in the DE config by default.

**Comment by unplannedlunch** [comment]
Just ran into this as well. The "Into the Microverse" chapter of the questbook says that draconium ore can be found all around the End, but I can't find either the DE nor GT versions of the ore.

**Comment by Miczu555PL** [comment]
"No such thing as draconium."
`[11:35:36] [Server thread/INFO]: Initializing ore generation registry...
[11:35:36] [Server thread/INFO]: Reloading ore generation files from config...
[11:35:36] [Server thread/ERROR]: Failed to parse worldgen definition end/draconium_vein.json on path <serverdirpath>\Nomifactory CEu Server\config\gregtech\worldgen\vein\end\draconium_vein.json
java.lang.IllegalArgumentException: Material with name draconium not found!
	at gregtech.api.worldgen.config.OreConfigUtils.getMaterialByName(OreConfigUtils.java:81) ~[OreConfigUtils.class:?]
	at gregtech.api.worldgen.config.OreConfigUtils.getOreStateMap(OreConfigUtils.java:56) ~[OreConfigUtils.class:?]
	at gregtech.api.worldgen.config.FillerConfigUtils.createSimpleFiller(FillerConfigUtils.java:69) ~[FillerConfigUtils.class:?]
	at gregtech.api.worldgen.config.FillerConfigUtils.createBlockStateFiller(FillerConfigUtils.java:33) ~[FillerConfigUtils.class:?]
	at gregtech.api.worldgen.config.FillerConfigUtils.readLayerFiller(FillerConfigUtils.java:137) ~[FillerConfigUtils.class:?]
	at gregtech.api.worldgen.config.FillerConfigUtils.createLayeredFiller(FillerConfigUtils.java:130) ~[FillerConfigUtils.class:?]
	at gregtech.api.worldgen.filler.LayeredBlockFiller.loadFromConfig(LayeredBlockFiller.java:24) ~[LayeredBlockFiller.class:?]
	at gregtech.api.worldgen.config.WorldGenRegistry.createBlockFiller(WorldGenRegistry.java:617) ~[WorldGenRegistry.class:?]
	at gregtech.api.worldgen.config.OreDepositDefinition.initializeFromConfig(OreDepositDefinition.java:84) ~[OreDepositDefinition.class:?]
	at gregtech.api.worldgen.config.WorldGenRegistry.reinitializeRegisteredVeins(WorldGenRegistry.java:267) [WorldGenRegistry.class:?]
	at gregtech.api.worldgen.config.WorldGenRegistry.initializeRegistry(WorldGenRegistry.java:123) [WorldGenRegistry.class:?]
	at gregtech.core.CoreModule.init(CoreModule.java:247) [CoreModule.class:?]
	at gregtech.modules.ModuleManager.onInit(ModuleManager.java:138) [ModuleManager.class:?]
	at gregtech.GregTechMod.init(GregTechMod.java:67) [GregTechMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_411]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_411]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]
[11:35:36] [Server thread/ERROR]: Failed to parse worldgen definition moon/fluorite_vein.json on path <serverdirpath>\Nomifactory CEu Server\config\gregtech\worldgen\vein\moon\fluorite_vein.json
java.lang.IllegalArgumentException: Material with name fluorite not found!
	at gregtech.api.worldgen.config.OreConfigUtils.getMaterialByName(OreConfigUtils.java:81) ~[OreConfigUtils.class:?]
	at gregtech.api.worldgen.config.OreConfigUtils.getOreStateMap(OreConfigUtils.java:56) ~[OreConfigUtils.class:?]
	at gregtech.api.worldgen.config.FillerConfigUtils.createSimpleFiller(FillerConfigUtils.java:69) ~[FillerConfigUtils.class:?]
	at gregtech.api.worldgen.config.FillerConfigUtils.createBlockStateFiller(FillerConfigUtils.java:33) ~[FillerConfigUtils.class:?]
	at gregtech.api.worldgen.config.FillerConfigUtils.createWeightRandomStateFiller(FillerConfigUtils.java:117) ~[FillerConfigUtils.class:?]
	at gregtech.api.worldgen.config.FillerConfigUtils.createBlockStateFiller(FillerConfigUtils.java:45) ~[FillerConfigUtils.class:?]
	at gregtech.api.worldgen.filler.SimpleBlockFiller.loadFromConfig(SimpleBlockFiller.java:27) ~[SimpleBlockFiller.class:?]
	at gregtech.api.worldgen.config.WorldGenRegistry.createBlockFiller(WorldGenRegistry.java:617) ~[WorldGenRegistry.class:?]
	at gregtech.api.worldgen.config.OreDepositDefinition.initializeFromConfig(OreDepositDefinition.java:84) ~[OreDepositDefinition.class:?]
	at gregtech.api.worldgen.config.WorldGenRegistry.reinitializeRegisteredVeins(WorldGenRegistry.java:267) [WorldGenRegistry.class:?]
	at gregtech.api.worldgen.config.WorldGenRegistry.initializeRegistry(WorldGenRegistry.java:123) [WorldGenRegistry.class:?]
	at gregtech.core.CoreModule.init(CoreModule.java:247) [CoreModule.class:?]
	at gregtech.modules.ModuleManager.onInit(ModuleManager.java:138) [ModuleManager.class:?]
	at gregtech.GregTechMod.init(GregTechMod.java:67) [GregTechMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_411]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_411]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_411]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_411]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]
[11:35:36] [Server thread/INFO]: Loaded 54 vein worldgen definitions
[11:35:36] [Server thread/INFO]: Loaded 11 bedrock worldgen definitions
[11:35:36] [Server thread/INFO]: Loaded 0 worldgen definitions from addon mods
[11:35:36] [Server thread/INFO]: Loaded 0 bedrock worldgen definitions from addon mods
[11:35:36] [Server thread/INFO]: Loaded 65 total worldgen definitions`

**Comment by lynxx131** [comment]
@IntegerLimit  This also appears to be the case for flourite

```
[09:47:33] [Client thread/ERROR] [GregTech]: Failed to parse worldgen definition moon/fluorite_vein.json on path D:\PrismLauncher\instances\nomi-ceu-cleanroom-1.7-alpha-4-client\.minecraft\config\gregtech\worldgen\vein\moon\fluorite_vein.json
java.lang.IllegalArgumentException: Material with name fluorite not found!
```

Would you be able to point me in the direction of the config that needs updating so I can address it locally until a fix is put in?

**Comment by IntegerLimit** [comment]
I'll check the whole config, should be fixed this week.

You can apply the fix from the PR diff when its done.

**Comment by Powah101** [comment]
> @IntegerLimit This also appears to be the case for flourite
> 
> ```
> [09:47:33] [Client thread/ERROR] [GregTech]: Failed to parse worldgen definition moon/fluorite_vein.json on path D:\PrismLauncher\instances\nomi-ceu-cleanroom-1.7-alpha-4-client\.minecraft\config\gregtech\worldgen\vein\moon\fluorite_vein.json
> java.lang.IllegalArgumentException: Material with name fluorite not found!
> ```
> 
> Would you be able to point me in the direction of the config that needs updating so I can address it locally until a fix is put in?

In case you didn't find it, go to mod options > Draconic Evolution > World > disableorespawnend

**Comment by IntegerLimit** [comment]
> > @IntegerLimit This also appears to be the case for flourite
> > ```
> > [09:47:33] [Client thread/ERROR] [GregTech]: Failed to parse worldgen definition moon/fluorite_vein.json on path D:\PrismLauncher\instances\nomi-ceu-cleanroom-1.7-alpha-4-client\.minecraft\config\gregtech\worldgen\vein\moon\fluorite_vein.json
> > java.lang.IllegalArgumentException: Material with name fluorite not found!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would you be able to point me in the direction of the config that needs updating so I can address it locally until a fix is put in?
> 
> In case you didn't find it, go to mod options > Draconic Evolution > World > disableorespawnend

That is not the right way to do it. NFu is meant to spawn our own Draconium Ore, and that config spawns Draconic Evolution's Draconium Ore.

**Comment by IntegerLimit** [comment]
Fixed. Download from [Nightly](https://nightly.link/Nomi-CEu/Nomi-CEu/workflows/testbuildpack/main) to get the patched version.
