### ISSUE TITLE
[Cleanroom] Minecraft loaded with groovy recipes missing

### ISSUE THREAD

**Issue by CrossElectronics** [Nomi-CEu/Nomi-CEu#932]
### Nomi CEu Version

1.7-beta-6a

### Launcher

Prism Launcher

### Configurations or Mods Changed

[+] Vintagium

### Environment

SP

### Mode

Expert Mode

### What Happened

On the first boot everything is OK. Starting up the second time, and the recipe error returns.

### Expected Behavior

Recipe loads correctly.

### Reproduction Steps

1. Open the game in Cleanroom w/ latest Fugue
2. Open your save and observe everything working as intended
3. Close the game
4. Open the game again and load up the save
5. The recipe error returns and some recipes fail to load.

### Logs
```
============  GroovyLog  ====  21.08.2024  ============
GroovyScript version: 1.1.3
[19:06:35] [CLIENT/INFO] [groovyscript]: Skipping load stage preInit, since no scripts are configured!
[19:06:55] [CLIENT/INFO] [redcore]: Skipping load stage init, since no scripts are configured!
[19:06:56] [CLIENT/INFO] [nomiceu]: Running scripts in loader 'postInit'
[19:06:56] [CLIENT/INFO] [nomiceu]:  - running org.codehaus.groovy.runtime.InvokerHelper$2
[19:06:56] [CLIENT/INFO] [nomiceu]:  - running postInit.Post-Initial.Main.General.Early-Game.earlygame
[19:06:57] [CLIENT/ERROR] [nomiceu]: An exception occurred while running scripts. Look at latest.log for a full stacktrace:
	java.lang.NoClassDefFoundError: net/minecraft/item/ItemStack
		at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
		at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
		at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603)
		at java.base/java.lang.Class.getMethods(Class.java:2185)
		at java.desktop/com.sun.beans.introspect.MethodInfo.get(MethodInfo.java:89)
		at java.desktop/com.sun.beans.introspect.ClassInfo.getMethods(ClassInfo.java:82)
		at java.desktop/java.beans.Introspector.getTargetMethodInfo(Introspector.java:1029)
		at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:446)
		at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:195)
		at groovy.lang.MetaClassImpl.lambda$addProperties$25(MetaClassImpl.java:3466)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
		at groovy.lang.MetaClassImpl.doPrivileged(MetaClassImpl.java:3519)
		at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3466)
		at groovy.lang.MetaClassImpl.reinitialize(MetaClassImpl.java:3448)
		at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3441)
		at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:272)
		at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:314)
		at postInit.Post-Initial.Main.General.Early-Game.earlygame.run(earlygame.groovy:20)
		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.runScript(GroovySandbox.java:167)
		at com.cleanroommc.groovyscript.sandbox.GroovyScriptSandbox.runScript(GroovyScriptSandbox.java:181)
		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.loadScripts(GroovySandbox.java:140)
```
### Additional Information
After deleting `.minecraft/cache/groovy`, the recipes load up correctly for once. When you reboot the game the error returns, although the error reported is *not exactly the same*
```
============  GroovyLog  ====  21.08.2024  ============
GroovyScript version: 1.1.3
[19:26:20] [CLIENT/INFO] [groovyscript]: Skipping load stage preInit, since no scripts are configured!
[19:26:40] [CLIENT/INFO] [redcore]: Skipping load stage init, since no scripts are configured!
[19:26:42] [CLIENT/INFO] [nomiceu]: Running scripts in loader 'postInit'
[19:26:42] [CLIENT/INFO] [nomiceu]:  - running org.codehaus.groovy.runtime.InvokerHelper$2
[19:26:42] [CLIENT/INFO] [nomiceu]:  - running postInit.Post-Initial.Main.General.Early-Game.earlygame
[19:26:42] [CLIENT/ERROR] [nomiceu]: An exception occurred while running scripts. Look at latest.log for a full stacktrace:
	java.lang.NoClassDefFoundError: net/minecraft/util/ResourceLocation        <== NOT SAME HERE
		at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
		at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
		at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603)
		at java.base/java.lang.Class.getMethods(Class.java:2185)
		at java.desktop/com.sun.beans.introspect.MethodInfo.get(MethodInfo.java:89)
		at java.desktop/com.sun.beans.introspect.ClassInfo.getMethods(ClassInfo.java:82)
		at java.desktop/java.beans.Introspector.getTargetMethodInfo(Introspector.java:1029)
		at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:446)
		at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:195)
		at groovy.lang.MetaClassImpl.lambda$addProperties$25(MetaClassImpl.java:3466)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
		at groovy.lang.MetaClassImpl.doPrivileged(MetaClassImpl.java:3519)
		at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3466)
		at groovy.lang.MetaClassImpl.reinitialize(MetaClassImpl.java:3448)
		at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3441)
		at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:272)
		at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:314)
		at postInit.Post-Initial.Main.General.Early-Game.earlygame.run(earlygame.groovy:20)
		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.runScript(GroovySandbox.java:167)
		at com.cleanroommc.groovyscript.sandbox.GroovyScriptSandbox.runScript(GroovyScriptSandbox.java:181)
		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.loadScripts(GroovySandbox.java:140)
```

**Comment by CrossElectronics** [comment]
![image](https://github.com/user-attachments/assets/0acf94be-ae41-4d23-a7f9-15e8656ab5a2)
Quick and dirty workaround for Linux

**Comment by IntegerLimit** [comment]
Yeah, the GrS cache has been... somewhat annoying for Cleanroom lately.

**Comment by IntegerLimit** [comment]
Fixed with updating cleanroom and fugue to latest.
