### ISSUE TITLE
Minecraft crashes When opening Energy Core GUI

### ISSUE THREAD

**Issue by hirrao** [Nomi-CEu/Nomi-CEu#936]
### Nomi CEu Version

1.7-beta-6a

### Launcher

Curseforge , also in HMCL

### Configurations or Mods Changed

Added AE2 Fluid Crafting Rework AE2-2.6.4-r
Added Flux Networks 1.12.2-4.1.1.34

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

While Opening Energy Core GUI for Draconic Evolution, Minecraft no response and crashes
![image](https://github.com/user-attachments/assets/49a9b370-0501-4e2e-88f8-756be572617f)

### Expected Behavior

no crash

### Reproduction Steps

Open Energy Core GUI

### Logs

https://mclo.gs/PZNGmA4

And
```
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// There are four lights!

Time: 2024-08-22 18:15:46 CST
Description: Error executing task

java.util.concurrent.ExecutionException: io.netty.util.IllegalReferenceCountException: refCnt: 0
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
    at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
    at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408)
    at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1347)
    at io.netty.buffer.UnpooledHeapByteBuf.copy(UnpooledHeapByteBuf.java:536)
    at io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:1163)
    at codechicken.lib.packet.PacketCustom.copy(PacketCustom.java:773)
    at codechicken.lib.packet.PacketCustom.toPacket(PacketCustom.java:320)
    at codechicken.lib.packet.PacketCustom.sendToPlayer(PacketCustom.java:359)
    at com.brandon3055.brandonscore.lib.datamanager.TileDataManager.lambda$detectAndSendChangesToListeners$1(TileDataManager.java:90)
    at com.brandon3055.brandonscore.utils.DataUtils.forEachMatch(DataUtils.java:101)
    at com.brandon3055.brandonscore.lib.datamanager.TileDataManager.detectAndSendChangesToListeners(TileDataManager.java:90)
    at com.brandon3055.brandonscore.inventory.ContainerBCBase.detectAndSendChanges(ContainerBCBase.java:61)
    at net.minecraft.inventory.Container.addListener(Container.java:53)
    at com.brandon3055.brandonscore.inventory.ContainerBCBase.addListener(ContainerBCBase.java:66)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:101)
    at com.brandon3055.draconicevolution.blocks.tileentity.TileEnergyStorageCore.onStructureClicked(TileEnergyStorageCore.java:151)
    at com.brandon3055.draconicevolution.blocks.tileentity.TileInvisECoreBlock.onTileClicked(TileInvisECoreBlock.java:72)
    at com.brandon3055.draconicevolution.blocks.InvisECoreBlock.onBlockActivated(InvisECoreBlock.java:73)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more

No Mixin Metadata is found in the Stacktrace.
```

### Additional Information

The save was created in 1.7-alpha-4

**Comment by v3ect0rgames** [comment]
Could Not Reproduce, maybe bad install? @IntegerLimit Probably knows

**Comment by v3ect0rgames** [comment]
Actually i think its a flux networks problem

**Comment by hirrao** [comment]
> Could Not Reproduce, maybe bad install, or corruption? @IntegerLimit Probably knows

install a new clean modpack and nothing changed，in discord someone have the same problem

**Comment by v3ect0rgames** [comment]
who in discord

**Comment by v3ect0rgames** [comment]
when you install a new clean modpack do you transfer the save?

**Comment by Folanlron** [comment]
My guess IDs are shifting every update for some odd reason, I'm not sure if you can get in to at least break the energy ball to replace the blocks?

(Also try and build a "new" one instead of trying to access the old one)

**Comment by IntegerLimit** [comment]
Will see if there are any issues with porting energy cores.

**Comment by hirrao** [comment]
> who in discord

https://discord.com/channels/927050775073534012/1072783298159452221/1275616107365007453
https://discord.com/channels/927050775073534012/1072783298159452221/1275253291130818582
like those

**Comment by hirrao** [comment]
> when you install a new clean modpack do you transfer the save?
i create a new creative saves，activate a energy core，use creative RF sources to charge it，and click the energy core，then crash happenes

**Comment by IntegerLimit** [comment]
I'm not sure, I can't reproduce.

Can you try using Prism Launcher instead of CurseForge Launcher?

**Comment by IntegerLimit** [comment]
Can you also send a screenshot of the setup?

**Comment by IntegerLimit** [comment]
If this issue really did only occur on the original save, that would probably be because... of 1.7-alpha-4, which corrupted worlds.

**Comment by hirrao** [comment]
> If this issue really did only occur on the original save, that would probably be because... of 1.7-alpha-4, which corrupted worlds.

I use Prism Launcher and have the same problem, this is the full log(uploaded from Prism Launcher)
https://mclo.gs/2HM3Rb7
I install a new modpack with no changes and create a new default world to test the problem
![image](https://github.com/user-attachments/assets/bd6ce0c7-0740-4a31-abaf-44f98bf8df3d)
After activating energy core, right click Energy core GUI(with charging), the first 30 seconds nothing happened, but then crashes.
Then I restart Minecraft 
![image](https://github.com/user-attachments/assets/87a7aa1c-42b7-4e20-a563-a30fa38fad13)
This time crashes happened less than 5s when I open the GUI

**Comment by hirrao** [comment]
> I'm not sure, I can't reproduce.
> 
> Can you try using Prism Launcher instead of CurseForge Launcher?

https://drive.google.com/file/d/1Mkx67q74BsEqKbL5XPdu0qeK0ala0_Vs/view?usp=drive_link
This video show how I cause this problem

**Comment by v3ect0rgames** [comment]
I replicated it

**Comment by IntegerLimit** [comment]
Ok, I will take a look. Thank you.
